# Generated by Django 5.0.3 on 2024-11-27 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_category_alter_blog_posted_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 27, 3, 42, 4, 42950), verbose_name='Опубликована'),
        ),
    ]
