# Generated by Django 5.0.3 on 2024-12-09 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cartitem_total_price_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 9, 23, 11, 5, 910410), verbose_name='Опубликована'),
        ),
    ]
