# Generated by Django 5.0.3 on 2024-12-09 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_cartitem_total_price_cartitem_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 10, 1, 7, 32, 313156), verbose_name='Опубликована'),
        ),
    ]
