# Generated by Django 5.0.3 on 2024-12-09 22:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 10, 1, 23, 18, 277010), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
    ]
