# Generated by Django 5.0.3 on 2024-12-11 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_cost_order_total_price_remove_order_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 11, 12, 48, 25, 806215), verbose_name='Опубликована'),
        ),
    ]
