# Generated by Django 5.0.3 on 2024-12-12 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_car_quantity_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 12, 17, 15, 11, 86557), verbose_name='Опубликована'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('brand', 'model', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'description')},
        ),
    ]
