# Generated by Django 5.0.3 on 2024-12-12 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_blog_posted_alter_car_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 13, 0, 12, 29, 200643), verbose_name='Опубликована'),
        ),
    ]
